server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: books
          uri: ${BOOK_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/books/**
        - id: auth
          uri: ${AUTH_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/auth/**